### ISSUE TITLE
Missing Line from magspoof.c

### ISSUE THREAD

**Issue by amustafa** [samyk/magspoof#12]
Line 31 of magspoof.c starts of with a string and line 33 ends with an closing semicolon that doesn't pair with anything.

Looking into the file history, it appears that the first line in this statement got deleted:

```
const char* tracks[] = {
"%B123456781234567^LASTNAME/FIRST^YYMMSSSDDDDDDDDDDDDDDDDDDDDDDDDD?\0", // Track 1
";123456781234567=YYMMSSSDDDDDDDDDDDDDD?\0" // Track 2
 };
```

**Comment by bugduino** [comment]
+1
