### ISSUE TITLE
Having a license?

### ISSUE THREAD

**Issue by ifraixedes** [samyk/magspoof#2]
Hi @samyk 

Nice job!

I would appreciate if you can define a license for all of this information; whatever you want, but it would be useful to know which one that leaving it under people and laws interpretations.

Thanks so much to release this information.

**Comment by madmod** [comment]
+1 This is an awesome project and I would like to know if I can make my own version of this for friends. Also I'm investigating an iPhone case version powered by the camera flash led.

**Comment by samyk** [comment]
I'll start reading up on licenses.

Great idea on one powered by the camera flash LED, that would be very cool. Please share any info if you do create that!

**Comment by ifraixedes** [comment]
@samyk thanks for your time to think about it

**Comment by Luabee** [comment]
Have you considered a license for this yet? I'm interested in building upon this project and selling it.

**Comment by samyk** [comment]
I've created and added a license, and will likely use this for future projects and all previous projects which are not yet licensed.

License added to git and provided at https://github.com/samyk/bpl/

**Comment by 0ki** [comment]
Is that a joke?
