### ISSUE TITLE
Second LED Missing From Schematic

### ISSUE THREAD

**Issue by SynapticRewrite** [samyk/magspoof#29]
Maybe this is a dumb question, but the photos (protoboard) show two LEDs but the diagram only has one? (Also, photos of the backside of the board would be *awesome*). I'm just trying to recreate it for fun.

**Comment by samyk** [comment]
I only used one ultimately. I had big plans for that second LED but ultimately simplified it. Just follow the schematic as it's much easier than the backside of the board.
