### ISSUE TITLE
Emulation issues using DIY MagSpoof

### ISSUE THREAD

**Issue by jLynx** [samyk/magspoof#31]
Hi All

So I have just built my first magspoof and seem to be have a few issues.

I brought a magnetic card reader to dump my card details. When I swipe my card with the reader I get:
`%B4548605864141234^JAMES SMITH              ^2107205100000000000000208000000?;4548605864141234=21072051000000000208?`
_(I have altered the data, THIS IS NOT MY ACTUAL CARD DATA)_

Now when I use my MagSpoof I have just created I get this:
Push button once:
`%B4548605864141234^JAMES SMITH              ^2107205100000000000000208000000?;E?+B4548605864141234^JAMES SMITH              ^2107205100000000000000208000000?`
Push button again (2nd time)
`%E?;4548601577143445=21072051000000000208?+4548601577143445=21072051000000000208?`

I would assume I just need to press the button once for it to print out just like it did when I originally swiped my card, but when I press the button the first time, it seems like it just prints Track 1 two times. once I press the button for a 2nd time, it seem to type Track 2 two times.

Does this seem like the correct behaviour, or have I done something wrong here?

Looking forward to getting this working :+1:

**Comment by samyk** [comment]
What did you define as track 1 and what as track 2?

**Comment by samyk** [comment]
Ah, I forgot about this https://github.com/samyk/magspoof/blob/master/magspoof.c#L148

When first playing the track, it will play both tracks, one after the other, attempting to fill both PoS' tracks buffers "separately"...this has always worked in my tests and allows playing two tracks "simultaneously" and having the PoS actually differentiate between them.

The 2nd button press only plays track 2, then it loops. You can adjust this in the main loop if you want to always playTrack(1) which will always (confusingly) play both tracks.

**Comment by jLynx** [comment]
Hi Samy
So what you are saying makes sense, now just confirming.
So 1 button press runs both tracks "at the same time". Which should work fine for most PoS terminals.
The 2nd button press is like a backup in case the PoS couldn't read track 2, so it plays it again? 

Then after that 2nd button press, the code restarts and plays the first track again when pressed(3rd press), etc etc etc

Would this be correct?

**Comment by samyk** [comment]
Correct.

**Comment by roboyaar** [comment]
hi sir
would you please guide me that on what amount did you set the fuse bit during the programming?
