### ISSUE TITLE
No signal with MSR605X

### ISSUE THREAD

**Issue by ghost** [samyk/magspoof#35]
I'm testing magspoof with a reader and writer MSR605X but is just ignored. I tried to send data to both heads but nothing the reader detect no signal.
Is there a special technology in other readers or maybe my self build magspoof is bad?
Thank you for the support.

**Comment by anybobynobody** [comment]
Do you have jabber ?

**Comment by samyk** [comment]
I tested on MSR605 with no issue but placement location was important. I'd measure the signal with an oscilloscope if you have one or can produce some simple microcontroller based one to see if you're getting any signal out on your magspoof.
