### ISSUE TITLE
Magspoof sounds different than a card

### ISSUE THREAD

**Issue by madmod** [samyk/magspoof#5]
I've constructed magspoof according to the schematic here with all the same parts as the video, except that it is on a breadboard and running at 5v. (I also tried 3.3v with the same results.) I acquired information from one of my cards with the Android app [Rhombus](https://github.com/sshipman/RhombusLib) and was able to place a zip tie in the Coin reader to get both tracks off my card. After programming my microcontroller with the card data I am unable to get it to function with the coin app or Rhombus which also accepts some partial data. After listening to the audio output of the coin in regular usage (swiping my card) and while held near my magspoof coil the difference in sound is apparent. The real card has a much softer quality and sounds a lot like sliding a card along a surface. In contrast holding the reader above my coil has greatly varying results depending on the position and orientation of the reader. If I hold the coin reader centered above the coil there is a relatively faint signal, while holding the center over the extreme edge of the coil produces a signal several times greater. Both have a harsh "digital" sound which is very unlike the normal card swipe. Also I believe the signal from magspoof was longer than the card swipe, but that may be only related to how quickly I moved the card. Hopefully I will be able to gain access to an oscilloscope for further testing in two weeks or so, but in the meantime I was wondering if anyone had any suggestions for how I might troubleshoot this further.

**Comment by samyk** [comment]
Yes, they will sound different but that is pretty irrelevant. A signal on a scope will help but I'd be more curious if your track data makes sense. If you can provide track data similar to yours with some numbers replaced with "9"s, then I can take a look to at least see if they're reasonable.
